server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:2345/OTM?createDatabaseIfNotExist=true
    esername: port
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
