server:
  port: 8976
spring:
  datasource:
    url: jdbc:mysql://localhost:1234/SOLID?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false

